name: build

on: [push, pull_request]

jobs:
  windows-msys:
    name: ${{ matrix.config }} Windows ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]
        cc: [gcc]
        include:
          - arch: x86
            msystem: MINGW32
            prefix: i686-w64-mingw32

          - arch: x86_64
            msystem: MINGW64
            prefix: x86_64-w64-mingw32

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: nasm
        msystem: ${{ matrix.msystem }}
        path-type: minimal
        release: false
        update: false

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: |
        ./configure --host=${{ matrix.prefix }} --enable-static --bit-depth=8 --disable-swscale --disable-lavf --disable-ffms --disable-gpac --disable-opencl --disable-interlaced --disable-lsmash --disable-gpl --enable-strip
        make -j 4
        mv x264.exe x264_${{ matrix.arch }}_8.exe
        make clean
        ./configure --host=${{ matrix.prefix }} --enable-static --bit-depth=10 --disable-swscale --disable-lavf --disable-ffms --disable-gpac --disable-opencl --disable-interlaced --disable-gpl --disable-lsmash --enable-strip
        make -j 4
        mv x264.exe x264_${{ matrix.arch }}_10.exe

    - uses: actions/upload-artifact@v3
      with:
        name: Windows (GCC)
        path: x264_*.exe
        if-no-files-found: error
#        retention-days: 5
