name: build

on: [push, pull_request]

jobs:
  windows-msys:
    name: ${{ matrix.config }} Windows ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]
        cc: [gcc]
        include:
          - arch: x86
            msystem: MINGW32
            prefix: mingw-w64-i686

          - arch: x86_64
            msystem: MINGW64
            prefix: mingw-w64-x86_64

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: ${{ matrix.prefix }}-binutils ${{ matrix.prefix }}-make ${{ matrix.prefix }}-${{ matrix.cc }}
        msystem: ${{ matrix.msystem }}
        path-type: minimal
        release: false
        update: false

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: |
        ./configure --enable-static --bit-depth=8 --disable-swscale --disable-lavf --disable-ffms --disable-gpac --disable-opencl --disable-interlaced --disable-lsmash --disable-gpl --enable-strip
        make -j 4
        make clean ARCH=${{ matrix.arch }}
        ./configure --enable-static --bit-depth=10 --disable-swscale --disable-lavf --disable-ffms --disable-gpac --disable-opencl --disable-interlaced --disable-gpl --disable-lsmash --enable-strip
        make -j 4
